name: deploy.yml

on:
  push:
    tags:        
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -U pyairtable
        pip install -U tqdm

    - name: executing setup w/ a particular tag
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
      run:
        python3 compile.py

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: re-compiled index.md